const snk = () => { 
	return `       
   ❒ RULES BOT JEPRI ❒

1. DILARANG TELFON BOT
2. DILARANG SPAM BOT
3. DILARANG BERKATA KASAR
4. DILARANG SPAM VIRTEX
7. DILARANG SPAM OWNER
8. DILARANG MASUKIN BOT KE GC TANPA IZIN OWNER
9. KASIH JEDA SAAT MENGGUNAKAN BOT

⚠️JIKA KALIAN MELANGGAR.. AKAN DI BLOCK + BANNED!!`
}

exports.snk = snk
